In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")

In [2]:
df = pd.read_csv("aqi_india_38cols_knn_final.csv")

df.head()

,city,state,latitude,longitude,datetime,month,day_name,is_weekend,season,time_of_day,...,no2_ugm3,so2_ugm3,o3_ugm3,dust_ugm3,aod,us_aqi,aqi_category,pm25_category_india,festival_period,crop_burning_season
0,agartala,tripura,23.8315,91.2868,2022-08-05 00:00:00,8.0,friday,False,monsoon,night,...,21.8,2.7,32.0,0.0,0.14,289.0,Very Unhealthy,good,False,False
1,agartala,tripura,23.8315,91.2868,2022-08-05 01:00:00,8.0,friday,False,monsoon,night,...,18.5,3.0,33.0,0.0,0.14,289.0,Very Unhealthy,good,False,False
2,agartala,tripura,23.8315,91.2868,2022-08-05 02:00:00,8.0,friday,False,monsoon,night,...,15.1,3.3,34.0,0.0,0.15,54.0,Moderate,good,False,False
3,agartala,tripura,23.8315,91.2868,2022-08-05 03:00:00,8.0,friday,False,monsoon,night,...,14.1,3.3,32.0,0.0,0.15,54.0,Moderate,good,False,False
4,agartala,tripura,23.8315,91.2868,2022-08-05 04:00:00,8.0,friday,False,monsoon,night,...,13.9,3.2,30.0,0.0,0.14,54.0,Moderate,good,False,False

In [3]:
cleaned_df = df.copy()

In [7]:
cleaned_df.isnull().sum()

city                   0
state                  0
latitude               0
longitude              0
datetime               0
month                  0
day_name               0
is_weekend             0
season                 0
time_of_day            0
humidity_percent       0
dew_point_c            0
wind_gusts_kmh         0
precipitation_mm       0
is_raining             0
heavy_rain             0
pressure_msl_hpa       0
cloud_cover_percent    0
pm2_5_ugm3             0
pm10_ugm3              0
co_ugm3                0
no2_ugm3               0
so2_ugm3               0
o3_ugm3                0
dust_ugm3              0
aod                    0
us_aqi                 0
aqi_category           0
pm25_category_india    0
festival_period        0
crop_burning_season    0
dtype: int64

In [8]:
cleaned_df.duplicated().sum()

np.int64(0)

In [9]:
cleaned_df["us_aqi"].describe()

count    539647.000000
mean         92.475352
std          47.488798
min          19.000000
25%          57.000000
50%          82.000000
75%         123.000000
max         289.000000
Name: us_aqi, dtype: float64

count    539647.000000
mean         70.720654
std          21.697442
min           3.000000
25%          57.000000
50%          75.000000
75%          89.000000
max         100.000000
Name: humidity_percent, dtype: float64

In [11]:
cleaned_df["latitude"].describe()

count    539647.000000
mean         24.045197
std           5.000546
min          12.971600
25%          23.022500
50%          24.817000
75%          27.338900
max          30.733300
Name: latitude, dtype: float64

In [12]:
cleaned_df["longitude"].describe()

count    539647.000000
mean         83.652178
std           7.426200
min          72.571400
25%          77.209000
50%          80.270700
75%          91.736200
max          94.108600
Name: longitude, dtype: float64

In [13]:
pollutants = [
    "pm2_5_ugm3",
    "pm10_ugm3",
    "co_ugm3",
    "no2_ugm3",
    "so2_ugm3",
    "o3_ugm3",
    "dust_ugm3"
]

cleaned_df[pollutants].describe()

,pm2_5_ugm3,pm10_ugm3,co_ugm3,no2_ugm3,so2_ugm3,o3_ugm3,dust_ugm3
count,539647.000000,539647.000000,539647.000000,539647.000000,539647.000000,539647.000000,539647.000000
mean,33.324040,54.106458,450.095540,16.222275,10.622149,78.248279,24.244877
std,29.014321,59.120332,389.641424,21.101217,14.711964,44.354965,86.737083
min,1.900000,2.300000,96.000000,0.000000,0.200000,0.000000,0.000000
25%,14.100000,20.100000,237.000000,3.600000,2.500000,45.000000,0.000000
50%,25.000000,37.500000,332.000000,8.600000,5.800000,72.000000,2.000000
75%,42.800000,65.000000,506.000000,19.400000,12.600000,106.000000,11.000000
max,183.500000,420.000000,2903.000000,122.100000,134.200000,228.000000,714.000000

In [14]:
bool_cols = cleaned_df.select_dtypes(include="bool").columns

for col in bool_cols:
    print(col)
    print(cleaned_df[col].value_counts())
    print("-"*40)

is_weekend
is_weekend
False    385327
True     154320
Name: count, dtype: int64
----------------------------------------
is_raining
is_raining
False    437317
True     102330
Name: count, dtype: int64
----------------------------------------
heavy_rain
heavy_rain
False    537761
True       1886
Name: count, dtype: int64
----------------------------------------
festival_period
festival_period
False    482815
True      56832
Name: count, dtype: int64
----------------------------------------
crop_burning_season
crop_burning_season
False    433039
True     106608
Name: count, dtype: int64
----------------------------------------

In [15]:
cleaned_df["datetime"] = pd.to_datetime(cleaned_df["datetime"])

In [16]:
cleaned_df.dtypes

city                           object
state                          object
latitude                      float64
longitude                     float64
datetime               datetime64[ns]
month                         float64
day_name                       object
is_weekend                       bool
season                         object
time_of_day                    object
humidity_percent              float64
dew_point_c                   float64
wind_gusts_kmh                float64
precipitation_mm              float64
is_raining                       bool
heavy_rain                       bool
pressure_msl_hpa              float64
cloud_cover_percent           float64
pm2_5_ugm3                    float64
pm10_ugm3                     float64
co_ugm3                       float64
no2_ugm3                      float64
so2_ugm3                      float64
o3_ugm3                       float64
dust_ugm3                     float64
aod                           float64
us_aqi                        float64
aqi_category                   object
pm25_category_india            object
festival_period                  bool
crop_burning_season              bool
dtype: object

In [17]:
cleaned_df = cleaned_df.sort_values("datetime")

In [18]:
cleaned_df.reset_index(drop=True, inplace=True)

In [19]:
print(cleaned_df.shape)

print(cleaned_df.isnull().sum().sum())

print(cleaned_df.duplicated().sum())

(539647, 31)
0
0

In [20]:
cleaned_df.groupby("city")["state"].nunique().sort_values(ascending=False)

city
agartala       1
ahmedabad      1
aizawl         1
bengaluru      1
bhopal         1
bhubaneswar    1
chandigarh     1
chennai        1
dehradun       1
delhi          1
gangtok        1
gurugram       1
guwahati       1
hyderabad      1
imphal         1
itanagar       1
jaipur         1
kohima         1
kolkata        1
Name: state, dtype: int64

In [21]:
cleaned_df[
    (cleaned_df["latitude"] < 6) |
    (cleaned_df["latitude"] > 38) |
    (cleaned_df["longitude"] < 68) |
    (cleaned_df["longitude"] > 98)
]

Empty DataFrame
Columns: [city, state, latitude, longitude, datetime, month, day_name, is_weekend, season, time_of_day, humidity_percent, dew_point_c, wind_gusts_kmh, precipitation_mm, is_raining, heavy_rain, pressure_msl_hpa, cloud_cover_percent, pm2_5_ugm3, pm10_ugm3, co_ugm3, no2_ugm3, so2_ugm3, o3_ugm3, dust_ugm3, aod, us_aqi, aqi_category, pm25_category_india, festival_period, crop_burning_season]
Index: []

[0 rows x 31 columns]

In [22]:
for col in pollutants:
    print(col, (cleaned_df[col] < 0).sum())

pm2_5_ugm3 0
pm10_ugm3 0
co_ugm3 0
no2_ugm3 0
so2_ugm3 0
o3_ugm3 0
dust_ugm3 0

In [23]:
(cleaned_df["us_aqi"] < 0).sum()

np.int64(0)

In [24]:
cleaned_df.to_csv(
    "cleaned_air_quality.csv",
    index=False
)

# Conclusion

Dataset Validation Summary

- No missing values
- No duplicate rows
- Datetime converted successfully
- Coordinates validated
- Pollutant values validated
- Boolean columns verified
- Dataset sorted chronologically

The dataset is clean and ready for Exploratory Data Analysis (EDA).